=== angelodel80/corsoCodifica/Materials/XSLT-477250download/ch11/xsd/meta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified"
   xmlns:xs="http://www.w3.org/2001/XMLSchema">
   
<!--   <xs:import namespace="http://www.w3.org/XML/1998/namespace"
   schemaLocation="xml.xsd"/>-->
   
   <xs:include schemaLocation="common.xsd"/>
   <xs:include schemaLocation="links.xsd"/>
   <xs:include schemaLocation="iso_lang.xsd"/>
   
    <!--resource metadata-->
   
    <xs:simpleType name="empty">
      <xs:restriction base="xs:string">
         <xs:enumeration value=""/>
      </xs:restriction>
   </xs:simpleType>
   
   <xs:complexType name="summaryType" mixed="true">
      <xs:sequence>
         <xs:group ref="phrase" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   
   <xs:element name="summary" type="summaryType"/>

   <xs:element name="entry">
      <xs:complexType>
         <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="agent" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="summary" type="summaryType"/>
            <xs:element ref="content" minOccurs="0"/>
            <xs:element ref="category" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="published" type="xs:string" minOccurs="0"/>
            <xs:element name="updated" type="xs:date" minOccurs="0"/>
         </xs:choice>
         <xs:attributeGroup ref="core"/>
         <xs:attribute name="lang" type="iso_639_3" use="optional"/>

      </xs:complexType>
   </xs:element>
   <xs:element name="agent">
      <xs:annotation>
         <xs:documentation>Individual or organization responsible for
            production, for example the author, contributor, or publisher. The
            contained role elements define the
            responsibility.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="role" minOccurs="1" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attributeGroup ref="termReference"/>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="role">
      <xs:complexType>
         <xs:attributeGroup ref="termReference"/>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="content">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="empty">
               <xs:attributeGroup ref="resourceReference"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="category">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="empty">
               <xs:attributeGroup ref="termReference"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>   
   
<!--   subject metadata  -->
      
   <xs:simpleType name="positionType">
      <xs:list itemType="xs:double"/>
   </xs:simpleType>
   
   <xs:element name="terms">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="p" minOccurs="0"/>
            <xs:sequence>
               <xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:element ref="related" minOccurs="0"/>
         </xs:sequence>
         <xs:attributeGroup ref="core"/>
         <xs:attribute name="fixed" default="no">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="yes"/>
                  <xs:enumeration value="no"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="scheme" type="xs:anyURI"/>
         <xs:attribute name="lang" type="iso_639_3" use="optional"/>
      </xs:complexType>
      <xs:unique name="term_id">
         <xs:selector xpath="term"/>
         <xs:field xpath="@xml:id"/>
      </xs:unique>
      <xs:keyref name="term_ref" refer="term_id">
         <xs:selector xpath="term/broader"/>
         <xs:field xpath="@term"/>
      </xs:keyref>
   </xs:element>
   
   <xs:element name="term">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="label"/>
            <xs:element ref="altlabel" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="object" minOccurs="0"/>
            <xs:element ref="definition"/>
            <xs:element ref="note" minOccurs="0"/>
            <xs:element ref="broader" minOccurs="0"/>
            <xs:element ref="relatedterm" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attributeGroup ref="core"/>
         <xs:attribute name="type" type="xs:string" use="optional"/>
      </xs:complexType>
      <xs:unique name="alt_lang">
         <xs:selector xpath="altlabel"/>
         <xs:field xpath="@lang"/>
      </xs:unique>
   </xs:element>
   
   <xs:element name="label">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string"/>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="altlabel">
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attributeGroup ref="termReference"/>
               <xs:attribute name="lang" type="iso_639_3"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="object">
      <xs:complexType>
         <xs:attribute name="src" type="xs:anyURI" use="required">
            <xs:annotation>
               <xs:documentation>Refers to a image resource
                  ID</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="definition" type="summaryType"/>
   
   <xs:element name="broader">
      <xs:complexType>
         <xs:attributeGroup ref="termReference"/>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="relatedterm">
      <xs:complexType>
         <xs:attributeGroup ref="termReference"/>
      </xs:complexType>
   </xs:element>     

   <xs:element name="related" type="linklistType"/>
   
</xs:schema>

=== angelodel80/corsoCodifica/Materials/XSLT-477250download/ch11/terms_xpath2.xml
<?xml version="1.0" encoding="UTF-8"?>
<terms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="meta.xsd">

   <term xml:id="axisStep">
      <label>Axis step</label>
      <definition>An axis step has an axis which specifies a direction of travel
         in the node tree in relation to the context node, such as
            <code>parent::</code> or <code>child::</code>. It also specifies a
         node test, which defines the nodes to select using the node name or
         type.</definition>
   </term>
   <term xml:id="constructorFunction">
      <label>Constructor function</label>
      <definition>The constructor function for a given type is used to convert
         instances of other atomic types into the given type.</definition>
   </term>
   <term xml:id="contextItem">
      <label>Context item</label>
      <definition>The item, an atomic value or node, currently being processed.
         When the context item is a node, it is also called the context
         node.</definition>
   </term>
   <term xml:id="contextPosition">
      <label>Context position</label>
      <definition>The position of the context item in the sequence of items
         being processed. The position changes whenever the context item
         changes, and is used to evaluate a predicate such as
            <code>para[1]</code>. The <code>position()</code> function may be
         used to return its value.</definition>
   </term>
   <term xml:id="currentDateTime.">
      <label>Current dateTime.</label>
      <definition>An implementation-dependent point in time, which can be
         retrieved by the <code>current-dateTime()</code> function. If called
         more than once during the execution of a stylesheet, this function
         always returns the same result.</definition>
   </term>
   <term xml:id="emptySequence">
      <label>Empty sequence</label>
      <definition>A sequence containing zero items.</definition>
   </term>

   <term xml:id="filterExpression">
      <label>Filter expression</label>
      <definition>A primary expression, such as a literal, variable reference or
         function call, followed by zero or more predicates. The result consists
         of the items returned by the primary expression, filtered by applying
         each predicate in turn.</definition>
   </term>
   <term xml:id="implicitTimezone.">
      <label>Implicit timezone.</label>
      <definition>An implementation-defined value of type
            <code>xs:dayTimeDuration</code> to be used when a date, time, or
         dateTime value that does not have a timezone is used in a comparison or
         arithmetic operation.</definition>
   </term>
   <term xml:id="node">
      <label>Node</label>
      <definition>One of the node types defined in XPath 2.0, for example
         document, element, or attribute.</definition>
   </term>
   <term xml:id="pathExpression">
      <label>Path expression</label>
      <definition>An expression used to locate nodes within trees, which
         consists of one or more steps, separated by "/" or "//".</definition>
   </term>
   <term xml:id="predicate">
      <label>Predicate</label>
      <definition>An expression contained in square brackets [] that filters the
         nodes selected in an step expression.</definition>
   </term>
   <term xml:id="primaryExpression">
      <label>Primary expressions</label>
      <definition>Expressions that are the basic primitives of the XPath
         language such as a literal, variable reference or function
         call.</definition>
   </term>
   <term xml:id="sequence">
      <label>Sequence</label>
      <definition>An ordered collection of zero or more items.</definition>
   </term>
   <term xml:id="step">
      <label>Step</label>
      <definition>Part of a path expression that generates a sequence of items
         and then filters the sequence by zero or more predicates. A step may be
         either an axis step or a filter expression.</definition>
   </term>
   <term xml:id="variableReference">
      <label>Variable reference</label>
      <definition>A variable reference is a QName specified in an
            <element>xsl:variable</element> or <element>xsl:param</element>
         element, and referred to in an XPath expression. It is preceded by a $
         sign to distinguish it from a reference to a source document element
         name.</definition>
   </term>
</terms>
